// Generated by CoffeeScript 1.5.0
(function() {

  window.test = function() {
    var countdown, num;
    return countdown = (function() {
      var _i, _results;
      _results = [];
      for (num = _i = 10; _i >= 1; num = --_i) {
        _results.push(num);
      }
      return _results;
    })();
  };

  window.problem1 = function(number) {
    var countdown, sum, x, _i, _j, _len, _ref, _results;
    countdown = (function() {
      _results = [];
      for (var _i = 1, _ref = number - 1; 1 <= _ref ? _i <= _ref : _i >= _ref; 1 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
    sum = 0;
    for (_j = 0, _len = countdown.length; _j < _len; _j++) {
      x = countdown[_j];
      if (x % 3 === 0 || x % 5 === 0) {
        sum = sum + x;
      }
    }
    return sum;
  };

  window.fib = function(number) {
    var sum, x, y, z;
    x = 1;
    y = 1;
    z = 0;
    sum = 0;
    while (x < 4000000) {
      z = x;
      x = x + y;
      y = z;
      if (x % 2 === 0) {
        sum = sum + x;
      }
    }
    if (x % 2 === 0) {
      sum = sum - x;
    }
    return console.log(sum3);
  };

}).call(this);
